export default {
  account: {
    bill: '/account/bill',
    plan: '/account/plan',
    currentPlan: '/account/plan/0',
    planCost: '/account/plan/balance',
  },
  appstore: '/appstore',
  contact: '/contact',
  online: '/online',
  setting: {
    base: '/setting/base',
    web: '/setting/web',
    weibo: '/setting/weibo',
    wechat: '/setting/wechat',
    voip: '/setting/voip',
    mail: '/setting/mail',
    assign: '/setting/assign',
    plugin: '/setting/plugin',
    sms: '/setting/sms',
    quickReply: '/setting/quick-reply',
  },
  media: {
    sms: '/media/sms',
  },
  message: {
    send: '/agent/send',
    list: '/agent/message',
    read: '/agent/read',
    agent: '/message/agent',
    undo: '/message/undo',
  },
  user: {
    offline: '/user/offline',
  },
  permission: '/permission',
  me: '/me',
  order: {
    list: '/order',
    shift: '/order/shift',
    category: '/order/category',
    launch: '/order/launch',
  },
  stats: {
    order: '/stats/order',
    headline: '/stats/headline',
    agent: '/stats/agent',
    evaluation: '/stats/evaluation',
    visit: '/stats/visit',
    agenttiming: '/stats/agenttiming',
  },
  member: '/member',
  group: '/group',
  tag: '/tag',
  track: '/track',
  visitor: '/visitor/online',
  agent: {
    online: '/agent/online',
    offline: '/agent/offline',
  },
  client: {
    online: '/client/online',
  },
  pay: '/account/pay',
};
